# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  push-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: CheckOut
      uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Deploy
      uses: cross-the-world/scp-pipeline@master
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USER }}
        pass: ${{ secrets.PASSWORD }}
        connect_timeout: 60s
        scp: |
          ./* => /home/pokedex-api
        last_ssh: |
          cd /home/pokedex-api
          pnpm i
          npx prisma generate
          pnpm build
          pm2 delete pokedexApi
          pm2 start --name pokedexApi dist/index.js
        
        
